import cart from "./modules/cart";
import favorites from "./modules/favorites";
import catalog from "./modules/catalog";
import load from "./modules/load";
import search from "./modules/search";
import counter from "./modules/counter";
import "./scss/style.scss";
load();
cart();
favorites();
catalog();
search();
counter();
